### ISSUE TITLE
Almost there . need help with 'NameError: name 'colorizer' is not defined'

### ISSUE THREAD

**Issue by bufordk** [daddyparodz/AutoDeOldifyLocal#7]
Hey Mate,
Great installer so far. I fixed a few things along the way but not sure how to fix this. If you have time to help that will be great.

Thanks
bk
![image](https://github.com/daddyparodz/AutoDeOldifyLocal/assets/35783603/2ba2fb95-496f-4d95-a792-4208171dcf48)

**Comment by daddyparodz** [comment]
Hi there,

Sorry for the late response; I didn’t have time to follow this project.

It looks like the issue you're encountering is because the model file isn't present in the `models` directory. To resolve this, you need to download the required model file and place it in the correct directory. Here’s how you can do that:

1. **Download the Model:**

   From the DeOldify folder, use one of the following commands to download the model file:

   **Using `wget`:**
   ```bash
   wget https://huggingface.co/spaces/aryadytm/photo-colorization/resolve/main/models/ColorizeArtistic_gen.pth?download=true -O models/ColorizeArtistic_gen.pth
   ```

   **Using `curl`:**
   ```bash
   curl -L https://huggingface.co/spaces/aryadytm/photo-colorization/resolve/main/models/ColorizeArtistic_gen.pth?download=true -o models/ColorizeArtistic_gen.pth
   ```

2. **Run the Colorizer:**

   After downloading the model, you can run the cells

   ```python
   colorizer = get_image_colorizer(artistic=True)
   ```

   Then proceed with running the Colorize cell.

This should resolve the issue and allow you to use the colorizer as expected.

**Comment by daddyparodz** [comment]
I have now updated the scripts with this fix. Please check it out.
